/** Explorer-local import path retained while the canonical types live in contracts. */
export {
  ACCESS_STATES,
  AUTHORITY_CLASSES,
  EXPLORER_VIEWS,
  FRESHNESS_STATUSES,
  RECORD_STATUSES,
  RECORD_TYPES,
  RIGHTS_STATES,
  TIMELINE_EVENT_KINDS,
} from "@gis-ai-go/contracts";

export type {
  AccessState,
  AuthorityClass,
  CatalogueBundle,
  CatalogueQueryAnalysis,
  CatalogueRecord,
  ExplorerState,
  ExplorerView,
  FacetOption,
  FacetOptions,
  FreshnessStatus,
  GraphAdjacency,
  GraphEdge,
  GraphModel,
  GraphNode,
  JsonPrimitive,
  JsonValue,
  PublicationEnvelope,
  RecordAccess,
  RecordAuthority,
  RecordFreshness,
  RecordRights,
  RecordStatus,
  RecordType,
  RightsState,
  TimelineEvent,
  TimelineEventKind,
  TimelineMissingSummary,
  TimelineModel,
} from "@gis-ai-go/contracts";
